### ISSUE TITLE
"pip install h5pyd" installs v0.3.3 instead of 0.4.0

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/h5pyd#63]
Running `pip install h5pyd` installs version 0.3.3 instead of the current 0.4.0.
```
$ pip --no-cache-dir install h5pyd
Collecting h5pyd
  Using cached https://files.pythonhosted.org/packages/4e/00/513f05db05e5dc3b599f541b042d8b47f9ec7c4ca62312f92fd33e11b607/h5pyd-0.3.3.tar.gz
Requirement already satisfied: ...
...
...
Building wheels for collected packages: h5pyd
  Building wheel for h5pyd (setup.py) ... done
...
Successfully built h5pyd
Installing collected packages: h5pyd
Successfully installed h5pyd-0.3.3
```
Other useful information:
```
$ python --version
Python 3.6.8
$ pip --version
pip 19.1.1
$ pip search h5pyd
h5pyd (0.4.0)  - h5py compatible client lib for HDF REST API
  INSTALLED: 0.3.3
  LATEST:    0.4.0
```
I know `pip` has had its issues over time but this is for a fairly fresh Python virtual environment and the latest `pip`.

**Comment by scottmn** [comment]
I ran into this as well.  The reason seems to be that the tar.gz file was not pushed to pypi.

0.3.3 has it, but 0.4.0 only has the binary

https://pypi.org/project/h5pyd/#files
https://pypi.org/project/h5pyd/0.3.3/#files

The maintainer would have to comment as to why this change.  As a workaround, install source from github:

`pip install https://github.com/HDFGroup/h5pyd/archive/v0.4.0.tar.gz`

**Comment by jreadey** [comment]
Mea culpa - I must have forgotten to upload the tar.gz file to PyPI last time.
I've pushed 0.4.4 out now.  Let me know if you have any issues with pip install.
